In [1]:
import pandas as pd
import numpy as np

import math

import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.preprocessing import LabelEncoder

import warnings
warnings.filterwarnings("ignore")

In [2]:
#Loading data into dataframe
MFCC_DF = pd.read_csv("../data/Anuran Calls (MFCCs)/Frogs_MFCCs.csv")
MFCC_DF

MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0          1.0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945   
1          1.0  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835   
2          1.0  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714   
3          1.0  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501   
4          1.0  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884   
...        ...       ...       ...       ...       ...       ...       ...   
7190       1.0 -0.554504 -0.337717  0.035533  0.034511  0.443451  0.093889   
7191       1.0 -0.517273 -0.370574  0.030673  0.068097  0.402890  0.096628   
7192       1.0 -0.582557 -0.343237  0.029468  0.064179  0.385596  0.114905   
7193       1.0 -0.519497 -0.307553 -0.004922  0.072865  0.377131  0.086866   
7194       1.0 -0.508833 -0.324106  0.062068  0.078211  0.397188  0.094596   

      MFCCs_ 8  MFCCs_ 9  MFCCs_10  ...  MFCCs_17  MFCCs_18  MFCCs_19  \
0    -0.150063 -0.171128  0.124676  ... -0.108351 -0.077623 -0.009568   
1    -0.222475 -0.207693  0.170883  ... -0.090974 -0.056510 -0.035303   
2    -0.242234 -0.219153  0.232538  ... -0.050691 -0.023590 -0.066722   
3    -0.194347 -0.098181  0.270375  ... -0.136009 -0.177037 -0.130498   
4    -0.265423 -0.172700  0.266434  ... -0.048885 -0.053074 -0.088550   
...        ...       ...       ...  ...       ...       ...       ...   
7190 -0.100753  0.037087  0.081075  ...  0.069430  0.071001  0.021591   
7191 -0.116460  0.063727  0.089034  ...  0.061127  0.068978  0.017745   
7192 -0.103317  0.070370  0.081317  ...  0.082474  0.077771 -0.009688   
7193 -0.115799  0.056979  0.089316  ...  0.051796  0.069073  0.017963   
7194 -0.117672  0.058874  0.076180  ...  0.061455  0.072983 -0.003980   

      MFCCs_20  MFCCs_21  MFCCs_22           Family      Genus  \
0     0.057684  0.118680  0.014038  Leptodactylidae  Adenomera   
1     0.020140  0.082263  0.029056  Leptodactylidae  Adenomera   
2    -0.025083  0.099108  0.077162  Leptodactylidae  Adenomera   
3    -0.054766 -0.018691  0.023954  Leptodactylidae  Adenomera   
4    -0.031346  0.108610  0.079244  Leptodactylidae  Adenomera   
...        ...       ...       ...              ...        ...   
7190  0.052449 -0.021860 -0.079860          Hylidae     Scinax   
7191  0.046461 -0.015418 -0.101892          Hylidae     Scinax   
7192  0.027834 -0.000531 -0.080425          Hylidae     Scinax   
7193  0.041803 -0.027911 -0.096895          Hylidae     Scinax   
7194  0.031560 -0.029355 -0.087910          Hylidae     Scinax   

             Species  RecordID  
0     AdenomeraAndre         1  
1     AdenomeraAndre         1  
2     AdenomeraAndre         1  
3     AdenomeraAndre         1  
4     AdenomeraAndre         1  
...              ...       ...  
7190     ScinaxRuber        60  
7191     ScinaxRuber        60  
7192     ScinaxRuber        60  
7193     ScinaxRuber        60  
7194     ScinaxRuber        60  

[7195 rows x 26 columns]

In [43]:
print("Size of dataset:", MFCC_DF.shape)

Size of dataset: (7195, 26)


# Explore the labels

In [3]:
MFCC_Fam = MFCC_DF['Family']
MFCC_Gen = MFCC_DF['Genus']
MFCC_Spe = MFCC_DF['Species']

print("Family Label\n")
print(MFCC_Fam.value_counts())
print("------------------------------------------------------------------")

print("Genus Label\n")
print(MFCC_Gen.value_counts())
print("------------------------------------------------------------------")

print("Species Label\n")
print(MFCC_Spe.value_counts())

Family Label

Leptodactylidae    4420
Hylidae            2165
Dendrobatidae       542
Bufonidae            68
Name: Family, dtype: int64
------------------------------------------------------------------
Genus Label

Adenomera        4150
Hypsiboas        1593
Ameerega          542
Dendropsophus     310
Leptodactylus     270
Scinax            148
Osteocephalus     114
Rhinella           68
Name: Genus, dtype: int64
------------------------------------------------------------------
Species Label

AdenomeraHylaedactylus    3478
HypsiboasCordobae         1121
AdenomeraAndre             672
Ameeregatrivittata         542
HypsiboasCinerascens       472
HylaMinuta                 310
LeptodactylusFuscus        270
ScinaxRuber                148
OsteocephalusOophagus      114
Rhinellagranulosa           68
Name: Species, dtype: int64


# Choose 70% of the data randomly as the training set.

In [4]:
X = MFCC_DF.iloc[:, :22]
y = MFCC_DF.iloc[:, 22:25]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# Standardize the features
std = StandardScaler()
X_train = std.fit_transform(X_train)
X_test = std.transform(X_test)

#Label encoding to convert categorical fatures
encoder = LabelEncoder()
train = y_train.apply(encoder.fit_transform)
test = y_test.apply(encoder.fit_transform)

train_Family = train.iloc[:, 0]
train_Genus = train.iloc[:, 1]
train_Species = train.iloc[:, 2]


test_Family = test.iloc[:, 0]
test_Genus = test.iloc[:, 1]
test_Species = test.iloc[:, 2]

In [44]:
print("Training dataset: ", X_train.shape)
print("Test dataset: ",X_test.shape)

Training dataset:  (5036, 22)
Test dataset:  (2159, 22)



Exact match- Fraction of sample that have all their labels classified correctly 

Hamming score - Proportion of incorrectly predicted labels to total number of labels

In [5]:
#Exact match score calculation

def get_exact_match(y_true, y_pred):
    exact_match_rows = np.all(y_true == y_pred, axis = 1)
    exact_match_count = np.sum(exact_match_rows)
    emr = exact_match_count/len(y_true)
    print("Exact match score: ",emr)
    return emr

In [6]:
#Hamming score calculation
def get_hamming(y_true, y_pred):
    incorrect_labels = np.logical_xor(y_true, y_pred)
    incorrect_labels_count = np.sum(incorrect_labels)
    hamming = 1-(incorrect_labels_count/len(y_true))
    print("Hamming Score: ",hamming)
    return hamming

#  Training a SVM for each of the labels, using Gaussian kernels and one versus all classifiers. Determining the weight of the SVM penalty and the width of the Gaussian Kernel using 10 fold cross validation.

In [7]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, f1_score

"""https://scikit-learn.org/stable/auto_examples/model_selection/plot_grid_search_digits.html"""

'https://scikit-learn.org/stable/auto_examples/model_selection/plot_grid_search_digits.html'

In [8]:
def getBestParams(classifier, settings, train_X, train_Y, test_X, test_Y):
    
    clf = GridSearchCV(estimator=classifier, **settings)
    %time clf.fit(train_X, train_Y)
    print("Grid scores :\n")
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"% (mean, std * 2, params))
    
    # output the best option
    print("\nOptimal parameters :")
    print(clf.best_params_, "\n")
    
    return clf.best_params_

In [9]:
def svc(X_train,train_Label,X_test,test_Label,param):
    svc = SVC(**param) # default - decision_function_shape='ovr'
    svc.fit(X_train, train_Label)
    return svc.predict(X_test)

In [10]:
# dict to store resukts of all gausian classifiers
SV_classifiers = {}
params = {'C' : np.logspace(1, 4, 4), 'gamma' : np.logspace(-3, 5, 10)}
kfold = StratifiedKFold(10, random_state=28, shuffle=True)
settings = {'cv' : kfold,'param_grid' : params,'scoring' : 'f1_weighted','verbose' : 1,'n_jobs':-1}

In [11]:
# Label - Family 
SV_classifiers['Family'] = getBestParams(SVC(kernel='rbf'), settings,X_train, train_Family, X_test, test_Family)

Fitting 10 folds for each of 40 candidates, totalling 400 fits
Wall time: 6min 26s
Grid scores :

0.948 (+/-0.018) for {'C': 10.0, 'gamma': 0.001}
0.986 (+/-0.012) for {'C': 10.0, 'gamma': 0.007742636826811269}
0.992 (+/-0.008) for {'C': 10.0, 'gamma': 0.05994842503189409}
0.974 (+/-0.010) for {'C': 10.0, 'gamma': 0.46415888336127775}
0.690 (+/-0.039) for {'C': 10.0, 'gamma': 3.593813663804626}
0.473 (+/-0.010) for {'C': 10.0, 'gamma': 27.825594022071257}
0.464 (+/-0.004) for {'C': 10.0, 'gamma': 215.44346900318823}
0.462 (+/-0.002) for {'C': 10.0, 'gamma': 1668.1005372000557}
0.462 (+/-0.002) for {'C': 10.0, 'gamma': 12915.496650148827}
0.462 (+/-0.002) for {'C': 10.0, 'gamma': 100000.0}
0.976 (+/-0.013) for {'C': 100.0, 'gamma': 0.001}
0.987 (+/-0.008) for {'C': 100.0, 'gamma': 0.007742636826811269}
0.992 (+/-0.009) for {'C': 100.0, 'gamma': 0.05994842503189409}
0.974 (+/-0.010) for {'C': 100.0, 'gamma': 0.46415888336127775}
0.690 (+/-0.039) for {'C': 100.0, 'gamma': 3.59381366380462

In [12]:
# Label - Genus 
SV_classifiers['Genus'] = getBestParams(SVC(kernel='rbf'), settings,X_train, train_Genus, X_test, test_Genus)

Fitting 10 folds for each of 40 candidates, totalling 400 fits
Wall time: 11min 21s
Grid scores :

0.955 (+/-0.025) for {'C': 10.0, 'gamma': 0.001}
0.987 (+/-0.011) for {'C': 10.0, 'gamma': 0.007742636826811269}
0.991 (+/-0.012) for {'C': 10.0, 'gamma': 0.05994842503189409}
0.950 (+/-0.017) for {'C': 10.0, 'gamma': 0.46415888336127775}
0.630 (+/-0.036) for {'C': 10.0, 'gamma': 3.593813663804626}
0.428 (+/-0.007) for {'C': 10.0, 'gamma': 27.825594022071257}
0.422 (+/-0.004) for {'C': 10.0, 'gamma': 215.44346900318823}
0.421 (+/-0.002) for {'C': 10.0, 'gamma': 1668.1005372000557}
0.421 (+/-0.002) for {'C': 10.0, 'gamma': 12915.496650148827}
0.421 (+/-0.002) for {'C': 10.0, 'gamma': 100000.0}
0.978 (+/-0.012) for {'C': 100.0, 'gamma': 0.001}
0.987 (+/-0.010) for {'C': 100.0, 'gamma': 0.007742636826811269}
0.991 (+/-0.012) for {'C': 100.0, 'gamma': 0.05994842503189409}
0.950 (+/-0.017) for {'C': 100.0, 'gamma': 0.46415888336127775}
0.630 (+/-0.036) for {'C': 100.0, 'gamma': 3.5938136638046

In [13]:
# Label - Species 
SV_classifiers['Species'] = getBestParams(SVC(kernel='rbf'), settings,X_train, train_Species, X_test, test_Species)

Fitting 10 folds for each of 40 candidates, totalling 400 fits
Wall time: 9min 39s
Grid scores :

0.967 (+/-0.015) for {'C': 10.0, 'gamma': 0.001}
0.987 (+/-0.008) for {'C': 10.0, 'gamma': 0.007742636826811269}
0.990 (+/-0.006) for {'C': 10.0, 'gamma': 0.05994842503189409}
0.939 (+/-0.020) for {'C': 10.0, 'gamma': 0.46415888336127775}
0.501 (+/-0.018) for {'C': 10.0, 'gamma': 3.593813663804626}
0.324 (+/-0.007) for {'C': 10.0, 'gamma': 27.825594022071257}
0.319 (+/-0.004) for {'C': 10.0, 'gamma': 215.44346900318823}
0.318 (+/-0.001) for {'C': 10.0, 'gamma': 1668.1005372000557}
0.318 (+/-0.001) for {'C': 10.0, 'gamma': 12915.496650148827}
0.318 (+/-0.001) for {'C': 10.0, 'gamma': 100000.0}
0.981 (+/-0.011) for {'C': 100.0, 'gamma': 0.001}
0.988 (+/-0.005) for {'C': 100.0, 'gamma': 0.007742636826811269}
0.990 (+/-0.008) for {'C': 100.0, 'gamma': 0.05994842503189409}
0.939 (+/-0.020) for {'C': 100.0, 'gamma': 0.46415888336127775}
0.501 (+/-0.018) for {'C': 100.0, 'gamma': 3.59381366380462

In [14]:
def get_Metrics(y_test, y_pred):
    
    cols = y_test.columns    
    for col in cols:
        print(classification_report(y_test[col], y_pred[col]))

In [15]:
emr_scores = {}
hamming_Scores ={}
#Predictions for all 3 labels
pred_Family = svc(X_train,train_Family,X_test,test_Family,SV_classifiers['Family'])
pred_Genus = svc(X_train,train_Genus,X_test,test_Genus,SV_classifiers['Genus'])
pred_Species = svc(X_train,train_Species,X_test,test_Species,SV_classifiers['Species'])

#Stack predictions and test for all 3 labels
y_test = np.column_stack((test_Family, test_Genus, test_Species))
y_pred = np.column_stack((pred_Family, pred_Genus, pred_Species))

#Get exact match ratio and Hamming score 
print("SVC with Gaussian Kernal Performance on test data:")
emr_scores['gaussian'] = get_exact_match(y_test, y_pred)
hamming_Scores['gaussian'] = get_hamming(y_test, y_pred)

SVC with Gaussian Kernal Performance on test data:
Exact match score:  0.9865678554886521
Hamming Score:  0.9916628068550255


In [16]:
#Classification report: Confusion matrix,f1-score
print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Family, pred_Family))
print('F1-score: %0.3f' % f1_score(test_Family, pred_Family, average='weighted'))

print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Genus, pred_Genus))
print('F1-score: %0.3f' % f1_score(test_Genus, pred_Genus, average='weighted'))

print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Species, pred_Species))
print('F1-score: %0.3f' % f1_score(test_Species, pred_Species, average='weighted'))

Evaluation of 'Family' label:

[[  25    0    2    0]
 [   0  162    0    0]
 [   0    0  620    3]
 [   1    0    8 1338]]
F1-score: 0.994
Evaluation of 'Family' label:

[[1245    0    1    4    0    1    0    0]
 [   0  162    0    0    0    0    0    0]
 [   2    0   81    1    0    0    0    0]
 [   0    0    0  467    0    1    0    0]
 [   0    0    0    3   93    0    0    0]
 [   0    0    0    5    0   29    0    0]
 [   0    0    0    2    0    0   25    0]
 [   1    0    0    1    0    0    0   35]]
F1-score: 0.990
Evaluation of 'Family' label:

[[ 215    0    0    0    2    2    0    1    0    0]
 [   0 1030    0    0    0    1    0    0    0    0]
 [   0    0  162    0    0    0    0    0    0    0]
 [   0    1    0   81    0    2    0    0    0    0]
 [   0    0    0    0  131    2    0    2    0    0]
 [   0    0    0    0    0  333    0    0    0    0]
 [   0    0    0    0    0    2   93    1    0    0]
 [   0    0    0    0    3    2    0   29    0    0]
 [   0    0  

#  Repeat  with L1-penalized SVMs

In [17]:
from sklearn.svm import LinearSVC

In [18]:
L1_penalized_classifiers = {}
params = {'C' : np.logspace(1, 5, 10)}
settings = {'cv' : kfold,'param_grid' : params,'scoring' : 'f1_weighted','verbose' : 1,'n_jobs':-1}

In [19]:
def lin_svc(X_train,train_Label,X_test,test_Label,param):
    svc = LinearSVC(**param,penalty='l1', dual=False)
    svc.fit(X_train, train_Label)
    return svc.predict(X_test)

In [20]:
# Label - Family 
L1_penalized_classifiers['Family'] = getBestParams(LinearSVC(penalty='l1', dual=False), settings,X_train, train_Family,\
                                                   X_test, test_Family)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Wall time: 51.9 s
Grid scores :

0.938 (+/-0.026) for {'C': 10.0}
0.938 (+/-0.026) for {'C': 27.825594022071243}
0.938 (+/-0.026) for {'C': 77.4263682681127}
0.938 (+/-0.026) for {'C': 215.44346900318823}
0.938 (+/-0.026) for {'C': 599.4842503189409}
0.938 (+/-0.026) for {'C': 1668.100537200059}
0.938 (+/-0.026) for {'C': 4641.588833612777}
0.938 (+/-0.026) for {'C': 12915.496650148827}
0.938 (+/-0.026) for {'C': 35938.13663804626}
0.938 (+/-0.026) for {'C': 100000.0}

Optimal parameters :
{'C': 10.0} 



In [21]:
# Label - Genus 
L1_penalized_classifiers['Genus'] = getBestParams(LinearSVC(penalty='l1', dual=False), settings,X_train, train_Genus, \
                                                  X_test, test_Genus)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Wall time: 1min 26s
Grid scores :

0.949 (+/-0.021) for {'C': 10.0}
0.949 (+/-0.022) for {'C': 27.825594022071243}
0.949 (+/-0.022) for {'C': 77.4263682681127}
0.949 (+/-0.022) for {'C': 215.44346900318823}
0.949 (+/-0.022) for {'C': 599.4842503189409}
0.949 (+/-0.022) for {'C': 1668.100537200059}
0.949 (+/-0.022) for {'C': 4641.588833612777}
0.949 (+/-0.022) for {'C': 12915.496650148827}
0.949 (+/-0.022) for {'C': 35938.13663804626}
0.949 (+/-0.022) for {'C': 100000.0}

Optimal parameters :
{'C': 27.825594022071243} 



In [22]:
# Label - Species 
L1_penalized_classifiers['Species'] = getBestParams(LinearSVC(penalty='l1', dual=False), settings,X_train, train_Species,\
                                                    X_test, test_Species)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Wall time: 1min 37s
Grid scores :

0.960 (+/-0.013) for {'C': 10.0}
0.960 (+/-0.013) for {'C': 27.825594022071243}
0.959 (+/-0.013) for {'C': 77.4263682681127}
0.959 (+/-0.013) for {'C': 215.44346900318823}
0.959 (+/-0.013) for {'C': 599.4842503189409}
0.959 (+/-0.013) for {'C': 1668.100537200059}
0.959 (+/-0.013) for {'C': 4641.588833612777}
0.959 (+/-0.013) for {'C': 12915.496650148827}
0.959 (+/-0.013) for {'C': 35938.13663804626}
0.959 (+/-0.013) for {'C': 100000.0}

Optimal parameters :
{'C': 10.0} 



In [23]:
#Predictions for all 3 labels
pred_Family = lin_svc(X_train,train_Family,X_test,test_Family,L1_penalized_classifiers['Family'])
pred_Genus = lin_svc(X_train,train_Genus,X_test,test_Genus,L1_penalized_classifiers['Genus'])
pred_Species = lin_svc(X_train,train_Species,X_test,test_Species,L1_penalized_classifiers['Species'])

#Stack predictions and test for all 3 labels
y_test = np.column_stack((test_Family, test_Genus, test_Species))
y_pred = np.column_stack((pred_Family, pred_Genus, pred_Species))

#Get exact match ratio and Hamming score 
print("L1-penalized SVC with Linear Kernal - Performance on test data:")
emr_scores['L-1 Linear'] = get_exact_match(y_test, y_pred)
hamming_Scores['L-1 Linear'] = get_hamming(y_test, y_pred)

L1-penalized SVC with Linear Kernal - Performance on test data:
Exact match score:  0.9124594719777674
Hamming Score:  0.9416396479851783


In [24]:
#Classification report: Confusion matrix,f1-score
print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Family, pred_Family))
print('F1-score: %0.3f' % f1_score(test_Family, pred_Family, average='weighted'))

print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Genus, pred_Genus))
print('F1-score: %0.3f' % f1_score(test_Genus, pred_Genus, average='weighted'))

print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Species, pred_Species))
print('F1-score: %0.3f' % f1_score(test_Species, pred_Species, average='weighted'))

Evaluation of 'Family' label:

[[   0    0   25    2]
 [   0  145    9    8]
 [   0    9  563   51]
 [   0   15   36 1296]]
F1-score: 0.922
Evaluation of 'Family' label:

[[1224   13    5    6    0    1    0    2]
 [   7  151    3    1    0    0    0    0]
 [  19    4   60    0    0    0    0    1]
 [  10    0    0  454    0    0    0    4]
 [   0    0    1    8   87    0    0    0]
 [   2    0    0   15    0   17    0    0]
 [   5    0    0   13    2    0    7    0]
 [   1    0    0    3    0    0    0   33]]
F1-score: 0.938
Evaluation of 'Family' label:

[[ 201    0   10    2    0    3    0    1    0    3]
 [   0 1030    1    0    0    0    0    0    0    0]
 [   1    0  153    4    0    3    0    0    1    0]
 [   3    9    5   65    0    1    0    0    0    1]
 [   3    0    0    0  130    2    0    0    0    0]
 [   0    2    0    0    1  325    1    0    1    3]
 [   1    0    0    1    3    5   86    0    0    0]
 [   1    0    0    0    6    5    0   22    0    0]
 [   0    0  

# Remedy class imbalance.

In [25]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=28)
X_train_Family_bal, train_Family_bal = smote.fit_resample(X_train, train_Family)
X_train_Genus_bal, train_Genus_bal = smote.fit_resample(X_train, train_Genus)
X_train_Species_bal, train_Species_bal = smote.fit_resample(X_train, train_Species)

L1_penalized_balanced_classifiers={}

In [26]:
# Label - Family 
L1_penalized_balanced_classifiers['Family'] = getBestParams(LinearSVC(penalty='l1', dual=False), settings,\
                                                            X_train_Family_bal,train_Family_bal,X_test, test_Family)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Wall time: 2min 51s
Grid scores :

0.949 (+/-0.011) for {'C': 10.0}
0.949 (+/-0.011) for {'C': 27.825594022071243}
0.949 (+/-0.011) for {'C': 77.4263682681127}
0.949 (+/-0.011) for {'C': 215.44346900318823}
0.949 (+/-0.011) for {'C': 599.4842503189409}
0.949 (+/-0.011) for {'C': 1668.100537200059}
0.949 (+/-0.011) for {'C': 4641.588833612777}
0.949 (+/-0.011) for {'C': 12915.496650148827}
0.949 (+/-0.011) for {'C': 35938.13663804626}
0.949 (+/-0.011) for {'C': 100000.0}

Optimal parameters :
{'C': 10.0} 



In [27]:
# Label - Genus 
L1_penalized_balanced_classifiers['Genus'] = getBestParams(LinearSVC(penalty='l1', dual=False), settings,X_train_Genus_bal, 
                                                           train_Genus_bal, X_test, test_Genus)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Wall time: 10min 6s
Grid scores :

0.957 (+/-0.005) for {'C': 10.0}
0.957 (+/-0.004) for {'C': 27.825594022071243}
0.957 (+/-0.004) for {'C': 77.4263682681127}
0.957 (+/-0.005) for {'C': 215.44346900318823}
0.957 (+/-0.004) for {'C': 599.4842503189409}
0.957 (+/-0.004) for {'C': 1668.100537200059}
0.957 (+/-0.004) for {'C': 4641.588833612777}
0.957 (+/-0.004) for {'C': 12915.496650148827}
0.957 (+/-0.004) for {'C': 35938.13663804626}
0.957 (+/-0.004) for {'C': 100000.0}

Optimal parameters :
{'C': 27.825594022071243} 



In [28]:
# Label - Species 
L1_penalized_balanced_classifiers['Species'] = getBestParams(LinearSVC(penalty='l1', dual=False), settings,X_train_Species_bal,
                                                             train_Species_bal,X_test, test_Species)

Fitting 10 folds for each of 10 candidates, totalling 100 fits
Wall time: 12min 51s
Grid scores :

0.963 (+/-0.004) for {'C': 10.0}
0.963 (+/-0.004) for {'C': 27.825594022071243}
0.963 (+/-0.004) for {'C': 77.4263682681127}
0.963 (+/-0.004) for {'C': 215.44346900318823}
0.963 (+/-0.004) for {'C': 599.4842503189409}
0.963 (+/-0.004) for {'C': 1668.100537200059}
0.963 (+/-0.004) for {'C': 4641.588833612777}
0.963 (+/-0.004) for {'C': 12915.496650148827}
0.963 (+/-0.004) for {'C': 35938.13663804626}
0.963 (+/-0.004) for {'C': 100000.0}

Optimal parameters :
{'C': 599.4842503189409} 



In [29]:
#Predictions for all 3 labels
pred_Family = lin_svc(X_train_Family_bal, train_Family_bal,X_test,test_Family,L1_penalized_balanced_classifiers['Family'])
pred_Genus = lin_svc(X_train_Genus_bal, train_Genus_bal,X_test,test_Genus,L1_penalized_balanced_classifiers['Genus'])
pred_Species = lin_svc(X_train_Species_bal, train_Species_bal,X_test,test_Species,\
                       L1_penalized_balanced_classifiers['Species'])

#Stack predictions and test for all 3 labels
y_test = np.column_stack((test_Family, test_Genus, test_Species))
y_pred = np.column_stack((pred_Family, pred_Genus, pred_Species))

#Get exact match ratio and Hamming score 
print("L1-penalized SVC with Linear Kernal and SMOTE - Performance on test data:")
emr_scores['L-1 Linear SMOTE'] = get_exact_match(y_test, y_pred)
hamming_Scores['L-1 Linear SMOTE'] = get_hamming(y_test, y_pred)

L1-penalized SVC with Linear Kernal and SMOTE - Performance on test data:
Exact match score:  0.8582677165354331
Hamming Score:  0.8948587308939324


In [30]:
#Classification report: Confusion matrix,f1-score
print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Family, pred_Family))
print('F1-score: %0.3f' % f1_score(test_Family, pred_Family, average='weighted'))

print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Genus, pred_Genus))
print('F1-score: %0.3f' % f1_score(test_Genus, pred_Genus, average='weighted'))

print("Evaluation of 'Family' label:\n") 
print(confusion_matrix(test_Species, pred_Species))
print('F1-score: %0.3f' % f1_score(test_Species, pred_Species, average='weighted'))

Evaluation of 'Family' label:

[[  24    0    2    1]
 [   0  158    1    3]
 [  18   31  534   40]
 [  25   31   46 1245]]
F1-score: 0.913
Evaluation of 'Family' label:

[[1117   32   44    8    1   21   22    6]
 [   2  155    3    2    0    0    0    0]
 [   5    2   75    0    0    0    1    1]
 [  11    0    2  430    1    9    8    7]
 [   0    0    1    5   87    1    2    0]
 [   0    0    0    4    0   30    0    0]
 [   0    0    0    1    1    0   25    0]
 [   0    0    0    1    0    0    1   35]]
F1-score: 0.912
Evaluation of 'Family' label:

[[ 197    0   10    5    0    2    0    2    1    3]
 [   0 1027    1    1    0    1    0    0    0    1]
 [   0    0  154    3    0    5    0    0    0    0]
 [   1    2    2   75    0    1    0    0    2    1]
 [   3    0    0    0  129    1    0    1    1    0]
 [   1    3    0    0    3  316    0    4    3    3]
 [   0    0    0    1    4    0   89    2    0    0]
 [   1    0    0    0    3    0    0   29    1    0]
 [   0    0  

# Conclusions:

In [31]:
summary = pd.DataFrame.from_dict([emr_scores, hamming_Scores])
indx = ['Exact Match Score','Hamming Score']
summary.index=indx
summary

gaussian  L-1 Linear  L-1 Linear SMOTE
Exact Match Score  0.986568    0.912459          0.858268
Hamming Score      0.991663    0.941640          0.894859

<b>Gaussian with standardization has the best exact match score and hamming score</b>

# 2. K-Means Clustering on a Multi-Class and Multi-Label Data Set

In [32]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_samples, silhouette_score

"""https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html"""

'https://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_silhouette_analysis.html'

In [33]:
def silhouette_score_K(num_cluster, X, rand):

    
    silhouette_avg_all = []
    for n in range(2, num_cluster + 1):
        clusterer = KMeans(n_clusters=n, random_state=rand)
        cluster_labels = clusterer.fit_predict(X)
        silhouette_avg_all.append(silhouette_score(X, cluster_labels))
        
    best_K = (silhouette_avg_all.index(max(silhouette_avg_all))) + 2 
    return best_K

In [34]:
X = MFCC_DF.iloc[:, :22]
Y = MFCC_DF.iloc[:, 22:25]

multi_labels = ['Family','Genus','Species']
# Get k with max silhoutter score for clustering
best_K = silhouette_score_K(50, X, 42)

print("The optimal k for clustering using silhouette score is:", best_K)

The optimal k for clustering using silhouette score is: 4


# In each cluster, determining which family is the majority by reading the true labels.Repeat for genus and species.

In [35]:
def getMajorityLabel(bestK, cluster_labels, Y): 
    
    majority_Label_Clusters = pd.DataFrame(columns=Y.columns)
    cluster_Y = Y
    cluster_Y['cluster_labels'] = cluster_labels
    label_Triplet =[]
    
    for lab in Y.columns:
        custer_maj = []
        for k in range(bestK):
            cluster_lab_majority = cluster_Y.groupby(['cluster_labels',lab]).size()[k].idxmax()
            custer_maj.append(cluster_lab_majority)
        majority_Label_Clusters[lab]= custer_maj
    return majority_Label_Clusters

In [36]:
# kmeans clustering
kmeans = KMeans(n_clusters=best_K, random_state=0)
cluster_Labels = kmeans.fit_predict(X)

# Majority label
print("Labels for each cluster:-")
cluster_Major_Label = getMajorityLabel(best_K, cluster_Labels, Y)
display(cluster_Major_Label)

Labels for each cluster:-


Family      Genus                 Species  cluster_labels
0  Leptodactylidae  Adenomera  AdenomeraHylaedactylus               0
1    Dendrobatidae   Ameerega      Ameeregatrivittata               1
2          Hylidae  Hypsiboas    HypsiboasCinerascens               2
3          Hylidae  Hypsiboas       HypsiboasCordobae               3

# For each cluster we have a majority label triplet (family, genus, species). Calculate the average Hamming distance, Hamming score, and Hamming loss)

<b>Hamming Distance:</b> Average of Sum of mismatched labels for all samples 

<b>Hamming Score:</b> Fraction of correct labels to total number of labels

<b>Hamming Loss:</b> Fraction of wrong labels to total number of labels

https://www.statology.org/hamming-distance-python

In [37]:
def get_hamming_metrics(cluster_Major_Label,cluster_Labels, Y):
    
    y_cluster = Y.copy()
    y_cluster['cluster_label'] = cluster_Labels
    
    #hamming_dist = 0
    hamming_dist1 = 0
    for cluster in range(len(cluster_Major_Label)):
        actual = y_cluster.groupby('cluster_label').get_group(cluster)
        pred = cluster_Major_Label.iloc[cluster,:]
        for index, row in actual.iterrows():
            hamming_dist1+=np.sum(np.not_equal(row[:3], pred[:3]))
            #hamming_dist+=distance.hamming(row[:3], pred[:3])
    hamming_distance1 = round(hamming_dist1/Y.shape[0],4)
    #hamming_distance = round(hamming_dist/Y.shape[0],4)
    hamming_loss = round(hamming_dist1/(Y.shape[0]*Y.shape[1]),4)   
    hamming_score = 1- hamming_loss
        
    return hamming_distance1, hamming_loss , hamming_score

In [38]:
hamming_distance, hamming_loss , hamming_score = get_hamming_metrics(cluster_Major_Label,cluster_Labels, Y)
print("Metrics:\n")
print("Average Hamming Distance = {}\nAverage Hamming Loss = {}\nAverage Hamming Score = {}\n".format(hamming_distance, hamming_loss , hamming_score))


Metrics:

Average Hamming Distance = 0.6653
Average Hamming Loss = 0.1663
Average Hamming Score = 0.8337



# Monte-Carlo Simulation

In [39]:
def monteCarloSimulation(max_iter, X, Y):   
    multi_labels = ['Family','Genus','Species']
    hamming_dist_all = []
    hamming_loss_all = []
    
    for itr in range(max_iter):
        # Get k with max silhoutte score for clustering
        best_K = silhouette_score_K(max_iter, X, itr)
        print("Iteration {} --> Optimal k ={}".format(itr+1, best_K))
        
        # kmeans clustering
        kmeans = KMeans(n_clusters=best_K, random_state=itr)
        cluster_Labels = kmeans.fit_predict(X)

        # Majority class for each label
        cluster_Major_Label = getMajorityLabel(best_K, cluster_Labels, Y)
        
        #Hamming distance, Hamming loss, Hamming Score
        hamming_distance, hamming_loss , hamming_score = get_hamming_metrics(cluster_Major_Label,cluster_Labels, Y)
        print("Hamming Distance : {}, Hamming Loss: {}, Hamming Score: {}\n".format(hamming_distance, hamming_loss , \
                                                                                    hamming_score))
        
        hamming_dist_all.append(hamming_distance)
        hamming_loss_all.append(hamming_loss)
        
    return hamming_dist_all, hamming_loss_all

In [40]:
X = MFCC_DF.iloc[:, :22]
Y = MFCC_DF.iloc[:, 22:25]   

hamming_dist, hamming_loss = monteCarloSimulation(50, X, Y)

hamming_diatnce_all = np.array(hamming_dist)
print("Average hamming distance = {}\nStandard deviation of hamming distance = {}".format(np.mean(hamming_diatnce_all),\
                                                                                         np.std(hamming_diatnce_all)))

Iteration 1 --> Optimal k =4
Hamming Distance : 0.6653, Hamming Loss: 0.1663, Hamming Score: 0.8337

Iteration 2 --> Optimal k =4
Hamming Distance : 0.6673, Hamming Loss: 0.1668, Hamming Score: 0.8331999999999999

Iteration 3 --> Optimal k =4
Hamming Distance : 0.7358, Hamming Loss: 0.1839, Hamming Score: 0.8161

Iteration 4 --> Optimal k =4
Hamming Distance : 0.6673, Hamming Loss: 0.1668, Hamming Score: 0.8331999999999999

Iteration 5 --> Optimal k =4
Hamming Distance : 0.6673, Hamming Loss: 0.1668, Hamming Score: 0.8331999999999999

Iteration 6 --> Optimal k =4
Hamming Distance : 0.6673, Hamming Loss: 0.1668, Hamming Score: 0.8331999999999999

Iteration 7 --> Optimal k =4
Hamming Distance : 0.6673, Hamming Loss: 0.1668, Hamming Score: 0.8331999999999999

Iteration 8 --> Optimal k =4
Hamming Distance : 0.6673, Hamming Loss: 0.1668, Hamming Score: 0.8331999999999999

Iteration 9 --> Optimal k =4
Hamming Distance : 0.6673, Hamming Loss: 0.1668, Hamming Score: 0.8331999999999999

Iterati

# Average and standard deviation of the 50 Hamming Distances 

In [41]:
print("Average hamming distance = {}\nStandard deviation of hamming distance = {}".format(np.mean(hamming_diatnce_all),\
                                                                                         np.std(hamming_diatnce_all)))

Average hamming distance = 0.6711919999999999
Standard deviation of hamming distance = 0.031020044100548917
